feat: Improve dialer pad and fix: app crash on number with char "+"
Chooloo/koler pull request #495
Opened 2022-12-03 02:43 UTC by xdubx

fix: https://github.com/Chooloo/koler/issues/441
feat: delete in the editText now works with the cursor position https://github.com/Chooloo/koler/issues/437
fix: replace the delete icon with the correct one https://github.com/Chooloo/koler/issues/486, add missing description

2023-01-12 14:52 UTC, roeiedri requested changes
Please fix those
If it's an issue ill just merge and change it myself

2023-01-12 14:52 UTC, roeiedri commented on chooloolib/src/main/java/com/chooloo/www/chooloolib/ui/dialpad/DialpadFragment.kt
> +            viewState.editTextRef.value = dialpadEditText
Please remove any view references from the viewstate
The view should listen for changes and act accordingly

2023-01-13 16:46 UTC, xdubx commented
Yes I take a look an correct it.

2023-01-15 21:26 UTC, xdubx commented
2/3 are now fixed? I close the pr

2023-01-15 21:26 UTC, closed without merging